USE Weddings; -- Using the final weddings dataset generated by Professor Chase

/* Select vendor info, department info, city info, pricing info, 
reviews and avg stars for each vendor */
SELECT v.vendor_id, v.vendor, d.function_id, d.functions, c.city, p.affordability, v.reviews, v.avg_stars
FROM vendors v /* Joining the vendors, cities, prices and departments tables */  
INNER JOIN cities c 
ON v.city_id = c.city_id
INNER JOIN prices p 
ON v.price_id = p.price_id
INNER JOIN departments d
ON v.function_id = d.function_id;


